import type { Ticket } from "./types";

export const TICKETS: Ticket[] = [
  {
    id: "bronze",
    name: "Bronze",
    price: "8,500 PKR",
    priceFull: "PKR 8,500",
    earlyBirdPrice: "6,500 PKR",
    capacity: 1200,
    gates: "4:00 PM",
    gateLabel: "Gate 4",
    minPerID: 5,
    maxPerID: 10,
    featured: false,
    color: "#CD7F32",
    features: [
      "Open-air general admission standing",
      "Delay speaker towers overhead for full-venue sound",
      "Open sightline to the main stage",
      "Bronze food court & washrooms",
      "Fast QR-scan entry — no ID check, just your QR",
    ],
    registration: {
      eyebrow: "Bronze",
      title: "General admission, open-air, big-festival atmosphere at the best entry price",
      body: "BRONZE — General Admission standing zone at the rear of the venue. The largest enclosure, split into Left and Right wings, giving you full access to the main stage experience. You'll hear the full sound system with delay speaker towers overhead and have a clear open-air sightline to the stage. Gates open 4:00 PM via Gate 4. Dedicated Bronze food court directly behind the zone — food, drinks, and washroom facilities on both flanks. Fast QR-scan entry — no ID check required at gate. Wristband issued on entry. No re-entry after exit.",
      highlights: [
        "First Light Founding Member - + PKR 1,500 per ticket",
        "Lucky draw: meet the headliner + Exclusive Stage Pass · Tier upgrade opportunity · Fast Lane at future OP events · Early access to future editions · Founding Members registry listing. Add for all tickets in this order.",
        "Up to 10 tickets per ID",
        "Each ticket carries a unique single-use QR code tied to one entry. Buy for your group in one go and share each person's QR before the gates.",
      ],
      agePolicy: "Age 15+ only.",
      idPolicy: "QR scan entry — no ID check required.",
      addOn: {
        label: "First Light Founding Member",
        price: "PKR 1,500",
        description:
          "Lucky draw: meet the headliner + Exclusive Stage Pass · Tier upgrade opportunity · Fast Lane at future OP events · Early access to future editions · Founding Members registry listing. Add for all tickets in this order.",
        defaultEnabled: true,
      },
    },
  },
  {
    id: "silver",
    name: "Silver",
    price: "12,500 PKR",
    priceFull: "PKR 12,500",
    earlyBirdPrice: "10,500 PKR",
    capacity: 445,
    gates: "4:00 PM",
    gateLabel: "Gate 3",
    minPerID: 5,
    maxPerID: 6,
    featured: false,
    color: "#C0C0C0",
    features: [
      "Spacious Silver standing enclosure",
      "Dedicated Silver gate (Gate 3)",
      "Full sound and screen coverage",
      "Food & beverage courts close by",
      "Single-use QR e-ticket",
    ],
    registration: {
      eyebrow: "Silver",
      title: "The heart of the crowd — full open-air standing with strong sightlines and festival energy",
      body: "SILVER — Spacious Silver standing enclosure positioned mid-field, directly behind the Gold zone. Standing zone with improved sightlines over the Bronze crowd. Full sound and screen coverage with dedicated audio delivery into this zone. Dedicated Silver food court on the left. Gates open 4:00 PM via Gate 3. Standard QR scan entry — no ID check required at gate. Wristband issued on entry. No re-entry after exit.",
      highlights: [
        "First Light Founding Member - + PKR 1,500 per ticket",
        "Lucky draw: meet the headliner + Exclusive Stage Pass · Tier upgrade opportunity · Fast Lane at future OP events · Early access to future editions · Founding Members registry listing. Add for all tickets in this order.",
        "Up to 6 tickets per ID",
        "Each ticket carries a unique single-use QR code tied to one entry. Buy for your group in one go and share each person's QR before the gates.",
      ],
      agePolicy: "Age 15+ only.",
      idPolicy: "QR scan entry — no ID check required.",
      addOn: {
        label: "First Light Founding Member",
        price: "PKR 1,500",
        description:
          "Lucky draw: meet the headliner + Exclusive Stage Pass · Tier upgrade opportunity · Fast Lane at future OP events · Early access to future editions · Founding Members registry listing. Add for all tickets in this order.",
        defaultEnabled: true,
      },
    },
  },
  {
    id: "vip",
    name: "VIP",
    price: "30,000 PKR",
    priceFull: "PKR 30,000",
    earlyBirdPrice: "25,000 PKR",
    capacity: 50,
    gates: "4:00 PM",
    gateLabel: "Gate 1",
    minPerID: 1,
    maxPerID: 5,
    featured: true,
    color: "#4B0082",
    features: [
      "Premium VIP standing enclosure with elevated sightlines",
      "Fast-track entry via Gate 1",
      "VIP bar access",
      "Upgraded washrooms and dedicated F&B points",
      "Early entry from 4:00 PM to settle in before the show",
      "ID-matched entry",
    ],
    registration: {
      eyebrow: "VIP",
      title: "An elevated standing enclosure with a clean line to the stage, VIP bar access, and a faster way in",
      body: "VIP — Premium VIP standing enclosure with elevated sightlines and dedicated hospitality. Separated from the general audience zones by barriers and dedicated stewarding. VIP bar access, upgraded washroom facilities, and dedicated F&B points. Fast-track entry via Gate 1 with no queuing. Early entry from 4:00 PM to settle in before the show. Photo ID required at gate — ID-matched entry. Wristband issued on entry. No re-entry after exit.",
      highlights: [
        "First Light Founding Member — + PKR 1,500 per ticket",
        "Lucky draw: meet the headliner + Exclusive Stage Pass · Tier upgrade opportunity · Fast Lane at future OP events · Early access to future editions · Founding Members registry listing. Add for all tickets in this order.",
        "Up to 5 tickets per ID — ID-matched entry",
        "Each ticket is registered to a unique government-issued ID. The name on your ticket must match your ID. Each ticket carries a unique single-use QR code.",
      ],
      agePolicy: "Age 18+ only for VIP.",
      idPolicy: "Government-issued Photo ID mandatory. ID-matched entry.",
      addOn: {
        label: "First Light Founding Member",
        price: "PKR 1,500",
        description:
          "Lucky draw: meet the headliner + Exclusive Stage Pass · Tier upgrade opportunity · Fast Lane at future OP events · Early access to future editions · Founding Members registry listing. Add for all tickets in this order.",
        defaultEnabled: true,
      },
    },
  },
  {
    id: "gold",
    name: "Gold",
    price: "18,500 PKR",
    priceFull: "PKR 18,500",
    earlyBirdPrice: "14,999 PKR",
    capacity: 200,
    gates: "4:15 PM",
    gateLabel: "Gate 2",
    minPerID: 5,
    maxPerID: 8,
    featured: false,
    color: "#FFD700",
    features: [
      "Gold standing zone toward the front of general admission",
      "Dedicated Gold gate (Gate 2)",
      "Gold food court & bar access",
      "Strong sightlines with full immersive sound coverage",
      "Single-use QR e-ticket with real-time gate validation",
    ],
    registration: {
      eyebrow: "GOLD",
      title: "Front-of-crowd general standing — close to the action without the PLATINUM price",
      body: "GOLD — Gold standing zone toward the front of general admission, positioned directly FOH-adjacent and as close to the stage as the general ticketing tiers allow. This is where you feel the full power of the sub-bass cluster and the stage production at maximum proximity. Barrier-separated from Silver behind. Dedicated Gold gate (Gate 2), Gold food court & bar access. Strong sightlines with full immersive sound coverage. Gates open 4:15 PM. Single-use QR e-ticket with real-time gate validation. Wristband issued on entry. No re-entry after exit.",
      highlights: [
        "First Light Founding Member — + PKR 1,500 per ticket",
        "Lucky draw: meet the headliner + Exclusive Stage Pass · Tier upgrade opportunity · Fast Lane at future OP events · Early access to future editions · Founding Members registry listing. Add for all tickets in this order.",
        "Up to 8 tickets per ID",
        "Each ticket carries a unique single-use QR code tied to one entry. Buy for your group in one go and share each person's QR before the gates.",
      ],
      agePolicy: "Age 15+ only.",
      idPolicy: "Single-use QR e-ticket with real-time gate validation.",
      addOn: {
        label: "First Light Founding Member",
        price: "PKR 1,500",
        description:
          "Lucky draw: meet the headliner + Exclusive Stage Pass · Tier upgrade opportunity · Fast Lane at future OP events · Early access to future editions · Founding Members registry listing. Add for all tickets in this order.",
        defaultEnabled: true,
      },
    },
  },
  {
    id: "gold-women",
    name: "Gold (Women's)",
    price: "14,999 PKR",
    priceFull: "PKR 14,999",
    earlyBirdPrice: "12,999 PKR",
    capacity: 200,
    gates: "4:15 PM",
    gateLabel: "Gate 2",
    minPerID: 1,
    maxPerID: 5,
    featured: false,
    color: "#FFD700",
    features: [
      "Women-only Gold enclosure (Pink Section)",
      "Dedicated female security and staff",
      "Same Gold-zone sightlines and sound",
      "Comfortable, priority entry via Gate 2",
      "Single-use QR e-ticket",
    ],
    registration: {
      eyebrow: "GOLD WOMEN",
      title: "A dedicated women-only enclosure inside the Gold zone — the same front-of-crowd energy in a secure, comfortable space",
      body: "GOLD (WOMEN'S) — A dedicated women-only enclosure (Pink Section) inside the Gold zone at the front of the audience field. Positioned directly FOH-adjacent for maximum stage production proximity and sound impact. Dedicated female security and staff. Same Gold-zone sightlines and sound. Comfortable, priority entry via Gate 2. Gates open 4:15 PM. Single-use QR e-ticket. Wristband issued on entry. No re-entry after exit.",
      highlights: [
        "First Light Founding Member — + PKR 1,500 per ticket",
        "Lucky draw: meet the headliner + Exclusive Stage Pass · Tier upgrade opportunity · Fast Lane at future OP events · Early access to future editions · Founding Members registry listing. Add for all tickets in this order.",
        "Up to 5 tickets per ID",
        "Each ticket carries a unique single-use QR code tied to one entry.",
      ],
      agePolicy: "Age 15+ only.",
      idPolicy: "Single-use QR e-ticket.",
      addOn: {
        label: "First Light Founding Member",
        price: "PKR 1,500",
        description:
          "Lucky draw: meet the headliner + Exclusive Stage Pass · Tier upgrade opportunity · Fast Lane at future OP events · Early access to future editions · Founding Members registry listing. Add for all tickets in this order.",
        defaultEnabled: true,
      },
    },
  },
  {
    id: "platinum",
    name: "PLATINUM",
    price: "50,000 PKR",
    priceFull: "PKR 50,000",
    earlyBirdPrice: "45,000 PKR",
    capacity: 5,
    gates: "4:30 PM",
    gateLabel: "Gate 1",
    minPerID: 1,
    maxPerID: 4,
    featured: true,
    color: "#000000",
    features: [
      "Front-of-stage PLATINUM standing zone — nearest to the headliner",
      "Dedicated PLATINUM gate with express security lane",
      "VIP Lounge & premium bar access",
      "Elevated finish and clearest sightline to the main stage",
      "Premium washrooms and shorter queues",
      "Dedicated PLATINUM food & beverage service",
      "ID-matched entry (name on ticket must match your CNIC/passport)",
    ],
    registration: {
      eyebrow: "PLATINUM",
      title: "The closest you can get — a dedicated stage-front zone with the best sightline in the house",
      body: "PLATINUM — The closest you can get. A dedicated stage-front zone with the best sightline in the house and priority on everything. Front-of-stage PLATINUM standing zone nearest to the headliner. Dedicated PLATINUM gate with express security lane via Gate 1. VIP Lounge & premium bar access. Elevated finish and clearest sightline to the main stage. Premium washrooms and shorter queues. Dedicated PLATINUM food & beverage service. ID-matched entry — name on ticket must match your CNIC/passport. Gates open 4:30 PM. Photo ID is mandatory — no exceptions. No re-entry after exit.",
      highlights: [
        "First Light Founding Member — + PKR 1,500 per ticket",
        "Lucky draw: meet the headliner + Exclusive Stage Pass · Tier upgrade opportunity · Fast Lane at future OP events · Early access to future editions · Founding Members registry listing. Add for all tickets in this order.",
        "Up to 4 tickets per ID — ID-matched entry",
        "Each ticket is registered to a unique government-issued ID. The name on your ticket must match your ID. Each ticket carries a unique single-use QR code.",
      ],
      agePolicy: "Age 18+ only for PLATINUM.",
      idPolicy: "Government-issued Photo ID mandatory. ID-matched entry.",
      addOn: {
        label: "First Light Founding Member",
        price: "PKR 1,500",
        description:
          "Lucky draw: meet the headliner + Exclusive Stage Pass · Tier upgrade opportunity · Fast Lane at future OP events · Early access to future editions · Founding Members registry listing. Add for all tickets in this order.",
        defaultEnabled: true,
      },
    },
  },
];

export const getTicketById = (id: string): Ticket => {
  const ticket = TICKETS.find((t) => t.id === id);
  if (!ticket) throw new Error(`Ticket not found: ${id}`);
  return ticket;
};
